### ISSUE TITLE
grouping apis matching a certain pattern for readability

### ISSUE THREAD

**Issue by xetova-technology** [rakutentech/laravel-request-docs#102] opened 2022-10-31 05:43 UTC
hello,

for readability purposes can the route list be grouped into cards?

![image](https://user-images.githubusercontent.com/87365741/198939402-32f08d7b-30a3-405d-a10b-5cb4510c583b.png)

for example
`/api/activity`
`/api/deals`

would be in different cards

Regards

**Comment by kevincobain2000** [comment] 2022-10-31 06:10
Yes we  are aware, we are going to be working on it

**Comment by kevincobain2000** [comment] 2022-10-31 06:13
Precisely we (@truongns and @kitloong and I) are working on UI renewal. Will address this issue in that.

**Comment by kevincobain2000** [comment] 2023-02-18 14:39
I ll close this issue as a duplicate of #121, however added a reference to this issue in #124 
However, well noted and will add group soon
Already added at-least sort and filter in #124

**Closed by kevincobain2000** 2023-02-18 14:39 UTC
